# Generated by Django 5.1.3 on 2024-11-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='item',
        ),
    ]
