# Generated by Django 5.1.3 on 2024-11-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_choice_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length=255),
        ),
    ]
