# Generated by Django 5.1.3 on 2024-11-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
