# Generated by Django 5.1.3 on 2024-11-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_choice_answer_alter_choice_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='topic',
            field=models.TextField(default='', max_length=255),
        ),
    ]
