# Generated by Django 5.1.3 on 2024-11-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
