# Generated by Django 5.1.3 on 2024-11-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_question_lordicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='lordicon',
        ),
        migrations.AddField(
            model_name='type',
            name='lordicon',
            field=models.TextField(default=''),
        ),
    ]
