# Generated by Django 5.1.3 on 2024-11-25 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_remove_question_lordicon_type_lordicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='question_id_test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='game.question'),
        ),
    ]
