# Generated by Django 5.1.3 on 2024-11-25 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_remove_choice_question_id_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type_choices', to='game.question'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_choices', to='game.question'),
        ),
    ]
