# Generated by Django 5.1.3 on 2024-11-25 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_choice_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='topic',
        ),
        migrations.AddField(
            model_name='question',
            name='type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type_question', to='game.type'),
        ),
    ]
