# Generated by Django 5.1.3 on 2024-11-25 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_remove_choice_topic_question_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
    ]
